"""create_comparison_chains_table

Revision ID: 0180ffca9fbb
Revises: 4f84c73706f5
Create Date: 2026-03-20 07:48:48.627919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0180ffca9fbb'
down_revision: Union[str, None] = '4f84c73706f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparison_chains',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_ids', sa.JSON(), nullable=False),
    sa.Column('comparison_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comparison_chains')
    # ### end Alembic commands ###
