"""add_category_to_npa_embeddings

Revision ID: 4f84c73706f5
Revises: f7b5709cd70e
Create Date: 2026-03-19 18:42:17.364487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f84c73706f5'
down_revision: Union[str, None] = 'f7b5709cd70e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('npa_embeddings', sa.Column('category', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_npa_embeddings_category'), 'npa_embeddings', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_npa_embeddings_category'), table_name='npa_embeddings')
    op.drop_column('npa_embeddings', 'category')
    # ### end Alembic commands ###
