"""initial_schema

Revision ID: c5033310208b
Revises: 
Create Date: 2026-03-17 21:55:53.168009

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5033310208b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False, comment='Отображаемое имя файла'),
    sa.Column('original_name', sa.String(length=500), nullable=False, comment='Оригинальное имя при загрузке'),
    sa.Column('file_type', sa.String(length=10), nullable=False, comment='Тип файла: docx или pdf'),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('structure_json', sa.JSON(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    op.create_table('npa_embeddings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('law_name', sa.String(length=500), nullable=False),
    sa.Column('article_number', sa.String(length=100), nullable=True),
    sa.Column('article_text', sa.Text(), nullable=False),
    sa.Column('hierarchy_level', sa.Integer(), nullable=False),
    sa.Column('pravo_by_guid', sa.String(length=200), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_npa_embeddings_law_name'), 'npa_embeddings', ['law_name'], unique=False)
    op.create_table('comparisons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doc_old_id', sa.String(length=36), nullable=False, comment='ID старой редакции'),
    sa.Column('doc_new_id', sa.String(length=36), nullable=False, comment='ID новой редакции'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('task_id', sa.String(length=200), nullable=True),
    sa.Column('total_risk_score', sa.Float(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doc_new_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doc_old_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparisons_doc_new_id'), 'comparisons', ['doc_new_id'], unique=False)
    op.create_index(op.f('ix_comparisons_doc_old_id'), 'comparisons', ['doc_old_id'], unique=False)
    op.create_table('diff_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('comparison_id', sa.String(length=36), nullable=False),
    sa.Column('section_path', sa.String(length=200), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('old_text', sa.Text(), nullable=True),
    sa.Column('new_text', sa.Text(), nullable=True),
    sa.Column('semantic_type', sa.String(length=50), nullable=True),
    sa.Column('law_reference', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('prosecutor_analysis_json', sa.JSON(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparisons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diff_results_comparison_id'), 'diff_results', ['comparison_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diff_results_comparison_id'), table_name='diff_results')
    op.drop_table('diff_results')
    op.drop_index(op.f('ix_comparisons_doc_old_id'), table_name='comparisons')
    op.drop_index(op.f('ix_comparisons_doc_new_id'), table_name='comparisons')
    op.drop_table('comparisons')
    op.drop_index(op.f('ix_npa_embeddings_law_name'), table_name='npa_embeddings')
    op.drop_table('npa_embeddings')
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
