"""add_mode_to_comparisons

Revision ID: f7b5709cd70e
Revises: 8284301928c8
Create Date: 2026-03-19 17:05:53.740589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b5709cd70e'
down_revision: Union[str, None] = '8284301928c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comparisons', sa.Column('mode', sa.String(length=20), nullable=False, server_default='pair'))
    op.alter_column('comparisons', 'doc_old_id',
               existing_type=sa.VARCHAR(length=36),
               comment='ID старой редакции / родительского НПА / единственного документа',
               existing_comment='ID старой редакции',
               existing_nullable=False)
    op.alter_column('comparisons', 'doc_new_id',
               existing_type=sa.VARCHAR(length=36),
               comment='ID новой редакции / дочернего ЛНА',
               existing_comment='ID новой редакции',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comparisons', 'doc_new_id',
               existing_type=sa.VARCHAR(length=36),
               comment='ID новой редакции',
               existing_comment='ID новой редакции / дочернего ЛНА',
               existing_nullable=False)
    op.alter_column('comparisons', 'doc_old_id',
               existing_type=sa.VARCHAR(length=36),
               comment='ID старой редакции',
               existing_comment='ID старой редакции / родительского НПА / единственного документа',
               existing_nullable=False)
    op.drop_column('comparisons', 'mode')
    # ### end Alembic commands ###
